### ISSUE TITLE
CI tests fail

### ISSUE THREAD

**Issue by teadur** [internetee/registrant_center#1]
@internetee/webexpert 
It seems that the included CI tests fail.
https://travis-ci.org/internetee/registrant_center/builds/526412472

Besides other failures it seems that semantic isnt built, how it should be built ? 
  12:8  error  Unable to resolve path to module '../../semantic/dist/semantic.min.css'  import/no-unresolved

**Comment by martin-we** [comment]
@teadur, I added semantic-ui dist folder.
E2E tests have an anomaly where they don't render pages anymore. This occured after updating dependecies.
Almost all unit tests fixed with latest commit.
Trying to get them fixed by today.

**Comment by teadur** [comment]
@martin-we looking forward for the tests to not failing then i can continue deployment to our infrastructure but i don't see point doing it before the tests don't fail anymore.

**Comment by vohmar** [comment]
Travis is all green
