### ISSUE TITLE
Validation error when changing phone number

### ISSUE THREAD

**Issue by OlegPhenomenon** [internetee/registrant_center#102]
It need to add a meaningful error when validating a phone number. For example, the user had a phone number of this format +372.5xxxxx then validation pass successful. 
If the user omits the country code in the phone, he will receive an error about invalid data. This error can confuse things a little, as happened in a recent case study. I suggest changing this error to a more meaningful one, for example, "you forgot to enter the country code in your phone number."

![Снимок экрана в 2021-12-08 14-00-46](https://user-images.githubusercontent.com/37714103/145205448-c263f5af-a957-4fca-8d48-3dd68ab70a05.png)
![Снимок экрана в 2021-12-08 14-01-01](https://user-images.githubusercontent.com/37714103/145205450-072d6e4a-a313-405d-8d0c-ee1091ce2a23.png)

**Comment by thiagoyoussef** [comment]
This issue is already solved: #104 - #105

![Captura de Tela 2022-04-12 às 09 50 05](https://user-images.githubusercontent.com/43591948/162899642-4cd0d273-521a-4bec-890b-795c55ed0314.png)
