### ISSUE TITLE
Replace MongoDB with Postgres

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [internetee/registrant_center#2]
There is no reason to store the session data in MongoDB, there is only one table that does not need to be clustered or distributed. Our infrastructure uses Postgres as data store, so there is compelling reason to introduce additional database engine to store user sessions. We have no experience in managing MongoDB clusters, and it also introduces another dependency for local development. In all fairness, we might even get by with SQLite, session data is not something that has tremendous value or needs to be maintained for a long time.

Express session supports several other backends, with a choice of them supporting Postgres. There is one for Sequelize, one for TypeORM and one for Knex.js. Any of them would work and allow us to maintain this software without the need for outside consultancy.

Provisional todo list:

- [ ] Replace Mongoose with Sequelize or other Javascript library that can talk to Postgres.
- [ ] Replace UserSchema.js with a Postgres equivalent
- [ ] Create database structure building script, can be as simple as a schema from pg_dump.
- [ ] Ensure that CI is configured to work with Postgres instead of Mongo.
- [ ] Replace queries written against MongoDB in callbackPageRoute.js with ones that work against Postgres library selected in step one.
- [ ] Create required database in staging environment, and then, in production.

**Comment by vohmar** [comment]
putting this issue on hold - effort needed here does not seem to justify itself at the moment as there is minimal data held in the MongoDB. Will return to this once we have some more use for the db or it starts to make trouble for ops.

**Comment by vohmar** [comment]
MongoDB is removed as the portal does not hold business registry cache locally any more.
