### ISSUE TITLE
Missing details in dashboard's tile layout

### ISSUE THREAD

**Issue by vohmar** [internetee/registrant_center#26]
The domain list in dashboard lacks regsitrant information (dashboard, tile layout) where user is able to extend the domain info. There is info about tech and admin contacts but not registrant.

Also in case of some registrars the reigstrar name is not displayed (eedirect is one such example in staging)

![image](https://user-images.githubusercontent.com/7734747/100352494-ba0f7400-2ff5-11eb-9984-d1cdbf8703f1.png)

**Comment by karlerikounapuu** [comment]
Registrar can appear as "-" when registrar's website address is not filled in registry side

**Comment by vohmar** [comment]
the missing registrant information is fixed by https://github.com/internetee/registrant_center/pull/24
as every registrar must have a web site to provide the registration service  the missing registrar reference in tile view should not be an issue in real life, so not going to spend any more time on this and closing the ticket. Thank you @karlerikounapuu
