### ISSUE TITLE
List of associated companies is not returned in profile

### ISSUE THREAD

**Issue by vohmar** [internetee/registrant_center#3]
In user profile "minu ettevõtted" no companies are displayed even though list is returned from the business registry as domains that the user is associated to only through a company are present in the domains list.

**Comment by vohmar** [comment]
API uuendus on nüüd toodangus:
https://github.com/internetee/registry/blob/master/doc/registrant-api/v1/companies.md

**Comment by vohmar** [comment]
The list of comapnies is now populated, but the records in the list are incremented by one each time user opens the list within a single session - looks like the list is cached somewhere, each time user accesses the list new query is sent to the registry, but cache is not cleared before adding new results to it.

**Comment by martin-we** [comment]
Duplication fixed in: https://github.com/internetee/registrant_center/commit/939b14d99fdd6d121d034c42ec36e8dd36c75fb9

**Comment by vohmar** [comment]
works as expected now - thank you!
