### ISSUE TITLE
Contact update does not work

### ISSUE THREAD

**Issue by vohmar** [internetee/registrant_center#61]
In production a private user updating their contact data will result in success message, poll message notification to registrar but no actual change of the data in the regsitry. This i was not able to replicate in staging

When manager is trying to update contact data of a business an error is returned "invalid data"

![image](https://user-images.githubusercontent.com/7734747/117293818-92f98000-ae7a-11eb-803b-810d583d638f.png)

**Comment by yulgolem** [comment]
OK, that's the request we are getting on registry side when trying to update org contact email:
```
Received update request
{"disclosed_attributes"=>[], "controller"=>"api/v1/registrant/contacts", "action"=>"update", "uuid"=>"b9d67696-35b2-46df-bd99-876b7410591d", "contact"=>{"disclosed_attributes"=>[]}}
```

The request is empty. Error message is received because we got `"contact"=>{"disclosed_attributes"=>[]}}`, which processed as
```
disclosed_attributes = reparsed_request_json[:disclosed_attributes]

if disclosed_attributes
  if contact.org?
    error_msg = "Legal person's data is visible by default and cannot be concealed." \
                  ' Please remove this parameter.'
    render json: { errors: [{ disclosed_attributes: [error_msg] }] }, status: :bad_request
  return
  end

  contact.disclosed_attributes = disclosed_attributes
end
```
