### ISSUE TITLE
Connect the propTypes library

### ISSUE THREAD

**Issue by OlegPhenomenon** [internetee/registrant_center#65]
From the official documentation: 

> As your app grows, you can catch a lot of bugs with typechecking. For some applications, you can use JavaScript extensions like Flow or TypeScript to typecheck your whole application. But even if you don’t use those, React has some built-in typechecking abilities

https://reactjs.org/docs/typechecking-with-proptypes.html#gatsby-focus-wrapper

JavaScript is a language with loose dynamic typing, and therefore, when passing parameters to components in react, you can shoot yourself in the foot by passing a completely different component and, accordingly, lead to unexpected behavior. Sometimes such errors are difficult to identify and it takes a lot of time; to solve this situation, I propose to connect the library propTypes

**Comment by vohmar** [comment]
fixed by https://github.com/internetee/registrant_center/pull/71
