### ISSUE TITLE
Generation of csv and pdf files without unnecessary requests

### ISSUE THREAD

**Issue by OlegPhenomenon** [internetee/registrant_center#74]
In order to download a csv or pdf file, the registrant center accesses the same endpoint as when downloading domains on the main page. Essentially, the data is the same.

It is necessary to get rid of unnecessary queries, in this context they are redundant, since the same endpoint and the same data are used.

**Comment by vohmar** [comment]
related to https://github.com/internetee/registrant_center/issues/72
closed by https://github.com/internetee/registrant_center/pull/75
