### ISSUE TITLE
Single domain objects should be queried using UUID

### ISSUE THREAD

**Issue by vohmar** [internetee/registrant_center#8]
Portal requests data for single domain objects from registrant API using domain name while it should use the UUID of that object

https://github.com/internetee/registry/blob/master/doc/registrant-api/v1/domain.md#get-apiv1registrantdomainsuuid

![image](https://user-images.githubusercontent.com/7734747/96886244-124dd600-148c-11eb-8098-d21c46ff99a5.png)

While in reality there might be no reason to make this query to registry at all as the portal already has all the details of the domains from initial domain list query. So it might be better to just reuse the cached data?

![image](https://user-images.githubusercontent.com/7734747/96886774-92743b80-148c-11eb-95af-e685f238eedf.png)

**Comment by vohmar** [comment]
UUID is used in now used in URLSs.

**Comment by martin-we** [comment]
WhoIs view domain links are fixed.
