### ISSUE TITLE
Automatically update contact object name using data from electronic identification process

### ISSUE THREAD

**Issue by vohmar** [internetee/registrant_center#9]
Contact data updating option enables only to update email address and phone number of the objects that belong to logged in user (same personal id number).

Add functionality to also update contact name if it differs from the one received from authentication process. This could be done automatically on first login or as a background job while user can freely use the portal for example.

![image](https://user-images.githubusercontent.com/7734747/96890693-9013e080-1490-11eb-8cd3-50dba092d540.png)

![image](https://user-images.githubusercontent.com/7734747/96890798-ad48af00-1490-11eb-9b2a-e2a7c8beb233.png)

**Comment by karlerikounapuu** [comment]
This is actually easier to implement in Registrant API side, as we're sending this data (full name, ident, country) anyway to the API at the moment.
